<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/Python-Notebook-Banners/Exercise.png"  style="display: block; margin-left: auto; margin-right: auto;";/>
</div>

# Exercise: Applying Pandas to strings

In this notebook, we test some of the concepts we've learned for Pandas application on strings.

## Learning objectives

By the end of this train, you should be able to:
- Demonstrate the ability to apply Pandas concepts in Python.

## Exercises

**Project scenario**: Environmental data analysis

**Background**: You are working with an environmental organisation that focuses on conserving natural habitats. You have been given a dataset containing detailed records of various conservation projects, environmental incidents, and initiatives. Your task is to extract and analyse specific information from this dataset to aid decision-making and reporting.

**Dataset structure**: The DataFrame `environment_df` contains the columns: 'ID', 'Description', 'Date', 'Location', 'Budget', and 'Notes'.

In [110]:
import pandas as pd
import re

data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Description': [
        'Forest Conservation Project in Spain',
        'River Cleanup Initiative Project 2021 in Portugal',
        'Urban Gardening Community Project in Germany',
        'Forest Reforestation Project 2022 in France',
        'Wildlife Protection Project Plan in Italy',
        'Endangered Species Conservation Project in Greece',
        'Wetland Restoration Project in Spain',
        'Marine Life Conservation Project in Portugal',
        'Air Quality Improvement Project Initiative in Germany',
        'Habitat Preservation Project for Birds in France'
    ],
    'Date': ['2021-03-15', '2021-06-20', '2022-01-11', '2022-04-05', '2023-02-22', '2023-05-30', '2021-09-13', '2022-07-19', '2023-03-08', '2022-11-21'],
    'Location': ['madrid, spain', 'LISBON, Portugal', 'berlin, germany', 'Paris, France', 'rome, Italy', 'Athens, GREECE', 'Valencia, Spain', 'PORTO, Portugal', 'Munich, Germany', 'Lyon, France'],
    'Budget': ['$20000', '€15000', '€12000', '£18000', '$25000', '€20000', '$17000', '€13000', '€11000', '£16000'],
    'Notes': [
        'Focusing on native forest species in Spain',
        'Cleanup of the Tagus river in Portugal. Endangered species alert!',
        'Community project in urban Berlin, Germany',
        'Reforestation of oak trees in Paris, France',
        'Plan for protecting local wildlife in Italy. Endangered species identified.',
        'Study on the impact on endangered bird species in Greece',
        'Restoration of wetlands in Valencia, Spain',
        'Conservation of marine life in Porto, Portugal',
        'Initiative for improving air quality in Munich, Germany',
        'Preservation of bird habitats in Lyon, France'
    ]
}



environment_df = pd.DataFrame(data)

print(environment_df)

   ID                                        Description        Date  \
0   1               Forest Conservation Project in Spain  2021-03-15
1   2  River Cleanup Initiative Project 2021 in Portugal  2021-06-20
2   3       Urban Gardening Community Project in Germany  2022-01-11
3   4        Forest Reforestation Project 2022 in France  2022-04-05
4   5          Wildlife Protection Project Plan in Italy  2023-02-22
5   6  Endangered Species Conservation Project in Greece  2023-05-30
6   7               Wetland Restoration Project in Spain  2021-09-13
7   8       Marine Life Conservation Project in Portugal  2022-07-19
8   9  Air Quality Improvement Project Initiative in ...  2023-03-08
9  10   Habitat Preservation Project for Birds in France  2022-11-21

           Location  Budget                                              Notes
0     madrid, spain  $20000         Focusing on native forest species in Spain
1  LISBON, Portugal  €15000  Cleanup of the Tagus river in Portugal. Endang...
2   berlin, germany  €12000         Community project in urban Berlin, Germany
3     Paris, France  £18000        Reforestation of oak trees in Paris, France
4       rome, Italy  $25000  Plan for protecting local wildlife in Italy. E...
5    Athens, GREECE  €20000  Study on the impact on endangered bird species...
6   Valencia, Spain  $17000         Restoration of wetlands in Valencia, Spain
7   PORTO, Portugal  €13000     Conservation of marine life in Porto, Portugal
8   Munich, Germany  €11000  Initiative for improving air quality in Munich...
9      Lyon, France  £16000      Preservation of bird habitats in Lyon, France

### Exercise 1

Standardise the format of the 'Location' column where each location should be in the format "City, Country". Additionally, extract the year from the 'Date' column and create a new column, 'Year'.

In [ ]:
# insert code here
extracted = environment_df['Location'].str.extract(r'([A-Za-z]+),\s*([A-Za-z]+)')
environment_df['Location'] = extracted[0].str.title() + ", " + extracted[1].str.title()

environment_df['year'] = environment_df['Date'].str.extract(r'(\b\d{4,}\b)')
environment_df

,ID,Description,Date,Location,Budget,Notes,year
0,1,Forest Conservation Project in Spain,2021-03-15,"Madrid, Spain",$20000,Focusing on native forest species in Spain,2021
1,2,River Cleanup Initiative Project 2021 in Portugal,2021-06-20,"Lisbon, Portugal",€15000,Cleanup of the Tagus river in Portugal. Endang...,2021
2,3,Urban Gardening Community Project in Germany,2022-01-11,"Berlin, Germany",€12000,"Community project in urban Berlin, Germany",2022
3,4,Forest Reforestation Project 2022 in France,2022-04-05,"Paris, France",£18000,"Reforestation of oak trees in Paris, France",2022
4,5,Wildlife Protection Project Plan in Italy,2023-02-22,"Rome, Italy",$25000,Plan for protecting local wildlife in Italy. E...,2023
5,6,Endangered Species Conservation Project in Greece,2023-05-30,"Athens, Greece",€20000,Study on the impact on endangered bird species...,2023
6,7,Wetland Restoration Project in Spain,2021-09-13,"Valencia, Spain",$17000,"Restoration of wetlands in Valencia, Spain",2021
7,8,Marine Life Conservation Project in Portugal,2022-07-19,"Porto, Portugal",€13000,"Conservation of marine life in Porto, Portugal",2022
8,9,Air Quality Improvement Project Initiative in ...,2023-03-08,"Munich, Germany",€11000,Initiative for improving air quality in Munich...,2023
9,10,Habitat Preservation Project for Birds in France,2022-11-21,"Lyon, France",£16000,"Preservation of bird habitats in Lyon, France",2022

### Exercise 2

Calculate the total budget allocated to "forest"-related projects. Assume that the 'Budget' column is in string format with various currency symbols, and convert it to a numeric format for calculations.

Hint:
1. Identify the currency of each budget amount.
2. Convert each amount to USD.
3. Sum the converted amounts.

In [157]:
# Fixed conversion rates

# Conversion rates
conversion_rates = {'$': 1.0, '€': 1.1, '£': 1.3}

# Extract symbol and number separately
environment_df[['Currency', 'Amount']] = environment_df['Budget'].str.extract(r'([$€£])(\d+)')

# Convert Amount to int
environment_df['Amount'] = environment_df['Amount'].astype(int)

# Map the currency to its conversion rate
environment_df['Rate'] = environment_df['Currency'].map(conversion_rates)

# Compute Budget in USD
environment_df['Budget_USD'] = environment_df['Amount'] * environment_df['Rate']

total_budget = environment_df['Budget_USD'].sum()

print(total_budget)


# insert code here

184300.0

### Exercise 3

Identify all records (`Notes` column) that mention endangered species and tag these records in a new column, '`Endangered_species`', with a 'Yes' or 'No' flag.

In [121]:
# insert code here
def endangered_species(text):
     
     endangered = re.search(r'(\bEndangered\b)', str(text))
     if endangered:
          return 'Yes'
     else:
          return 'No' 
     
environment_df['Endangered_species'] = environment_df['Notes'].apply(endangered_species)
environment_df

,ID,Description,Date,Location,Budget,Notes,year,Currency,Amount,Rate,Budget_USD,Endangered_species
0,1,Forest Conservation Project in Spain,2021-03-15,"Madrid, Spain",$20000,Focusing on native forest species in Spain,2021,$,20000,1.0,20000.0,No
1,2,River Cleanup Initiative Project 2021 in Portugal,2021-06-20,"Lisbon, Portugal",€15000,Cleanup of the Tagus river in Portugal. Endang...,2021,€,15000,1.1,16500.0,Yes
2,3,Urban Gardening Community Project in Germany,2022-01-11,"Berlin, Germany",€12000,"Community project in urban Berlin, Germany",2022,€,12000,1.1,13200.0,No
3,4,Forest Reforestation Project 2022 in France,2022-04-05,"Paris, France",£18000,"Reforestation of oak trees in Paris, France",2022,£,18000,1.3,23400.0,No
4,5,Wildlife Protection Project Plan in Italy,2023-02-22,"Rome, Italy",$25000,Plan for protecting local wildlife in Italy. E...,2023,$,25000,1.0,25000.0,Yes
5,6,Endangered Species Conservation Project in Greece,2023-05-30,"Athens, Greece",€20000,Study on the impact on endangered bird species...,2023,€,20000,1.1,22000.0,No
6,7,Wetland Restoration Project in Spain,2021-09-13,"Valencia, Spain",$17000,"Restoration of wetlands in Valencia, Spain",2021,$,17000,1.0,17000.0,No
7,8,Marine Life Conservation Project in Portugal,2022-07-19,"Porto, Portugal",€13000,"Conservation of marine life in Porto, Portugal",2022,€,13000,1.1,14300.0,No
8,9,Air Quality Improvement Project Initiative in ...,2023-03-08,"Munich, Germany",€11000,Initiative for improving air quality in Munich...,2023,€,11000,1.1,12100.0,No
9,10,Habitat Preservation Project for Birds in France,2022-11-21,"Lyon, France",£16000,"Preservation of bird habitats in Lyon, France",2022,£,16000,1.3,20800.0,No

### Exercise 4

Generate a report which shows, for each country, the number of projects, the average budget per project for that country, and a list of the top three most common project types across all the countries. Assume 'Project Type' is part of the 'Description' and can be obtained by finding the text before the word 'Project'.

In [160]:
# insert code here
# 1. Extract Project Type (text before the word "Project")
environment_df["Project_Type"] = environment_df["Description"].str.extract(r'(\w+)\s+Project')

# 2. Group by Country for number of projects + average budget
country_report = environment_df.groupby("Country").agg(
    num_projects=("Budget_USD", "count"),
    avg_budget=("Budget_USD", "mean")
).reset_index()

# 3. Get top 3 most common project types overall
top_projects = (
    environment_df["Project_Type"].value_counts()
    .head(3)
    .index.tolist()
)

# Final Report
report = {
    "Country Report": country_report,
    "Top 3 Project Types": top_projects
}

print(report)

{'Country Report':     Country  num_projects  avg_budget
0    France             2     22100.0
1   Germany             2     12650.0
2    Greece             1     22000.0
3     Italy             1     25000.0
4  Portugal             2     15400.0
5     Spain             2     18500.0, 'Top 3 Project Types': ['Conservation', 'Initiative', 'Community']}

## Solutions

### Exercise 1

In [155]:
# Standardising 'Location'
environment_df['Location'] = environment_df['Location'].apply(lambda x: x.title())

# Extracting 'Year'
environment_df['Year'] = pd.to_datetime(environment_df['Date']).dt.year
environment_df

,ID,Description,Date,Location,Budget,Notes,year,Currency,Amount,Rate,Budget_USD,Endangered_species,Project_type,Country,Project_Type,Year
0,1,Forest Conservation Project in Spain,2021-03-15,"Madrid, Spain",$20000,Focusing on native forest species in Spain,2021,$,20000,1.0,20000.0,No,Conservation,Spain,Conservation,2021
1,2,River Cleanup Initiative Project 2021 in Portugal,2021-06-20,"Lisbon, Portugal",€15000,Cleanup of the Tagus river in Portugal. Endang...,2021,€,15000,1.1,16500.0,Yes,Initiative,Portugal,Initiative,2021
2,3,Urban Gardening Community Project in Germany,2022-01-11,"Berlin, Germany",€12000,"Community project in urban Berlin, Germany",2022,€,12000,1.1,13200.0,No,Community,Germany,Community,2022
3,4,Forest Reforestation Project 2022 in France,2022-04-05,"Paris, France",£18000,"Reforestation of oak trees in Paris, France",2022,£,18000,1.3,23400.0,No,Reforestation,France,Reforestation,2022
4,5,Wildlife Protection Project Plan in Italy,2023-02-22,"Rome, Italy",$25000,Plan for protecting local wildlife in Italy. E...,2023,$,25000,1.0,25000.0,Yes,Protection,Italy,Protection,2023
5,6,Endangered Species Conservation Project in Greece,2023-05-30,"Athens, Greece",€20000,Study on the impact on endangered bird species...,2023,€,20000,1.1,22000.0,No,Conservation,Greece,Conservation,2023
6,7,Wetland Restoration Project in Spain,2021-09-13,"Valencia, Spain",$17000,"Restoration of wetlands in Valencia, Spain",2021,$,17000,1.0,17000.0,No,Restoration,Spain,Restoration,2021
7,8,Marine Life Conservation Project in Portugal,2022-07-19,"Porto, Portugal",€13000,"Conservation of marine life in Porto, Portugal",2022,€,13000,1.1,14300.0,No,Conservation,Portugal,Conservation,2022
8,9,Air Quality Improvement Project Initiative in ...,2023-03-08,"Munich, Germany",€11000,Initiative for improving air quality in Munich...,2023,€,11000,1.1,12100.0,No,Improvement,Germany,Improvement,2023
9,10,Habitat Preservation Project for Birds in France,2022-11-21,"Lyon, France",£16000,"Preservation of bird habitats in Lyon, France",2022,£,16000,1.3,20800.0,No,Preservation,France,Preservation,2022

**Standardising 'Location'**: This line converts all characters in the 'Location' column to title case (first letter of each word capitalised). It ensures consistency in the format of location names.

**Extracting 'Year'**: This line extracts the year from the 'Date' column. It first converts the 'Date' column to a datetime object using `pd.to_datetime` and then extracts the year component from this datetime object, adding it as a new column, 'Year', in the DataFrame.

### Exercise 2

In [156]:
# Fixed conversion rates
conversion_rates = {'$': 1.0, '€': 1.1, '£': 1.3}  # Example rates: 1 Euro = 1.1 USD, 1 Pound = 1.3 USD

def convert_to_usd(budget_str):
    # Extracting the currency symbol and amount
    currency_symbol = budget_str[0]
    amount = float(budget_str[1:])

    # Converting to USD
    if currency_symbol in conversion_rates:
        return amount * conversion_rates[currency_symbol]
    else:
        return amount

# Converting 'Budget' to numeric USD values
environment_df['Budget_USD'] = environment_df['Budget'].apply(convert_to_usd)

# Calculating total budget for "forest"-related projects in USD
total_budget_forest_usd = environment_df[environment_df['Description'].str.contains("forest", case=False)]['Budget_USD'].sum()
print(total_budget_forest_usd)

43400.0

* The `convert_to_usd` function extracts the currency symbol and amount from each budget string. It then converts the amount to USD using the given conversion rates.
* We then apply this function to the 'Budget' column to create a new 'Budget_USD' column, where all values are in USD.
* Finally, we calculate the total budget for "forest"-related projects using this standardised 'Budget_USD' column.

### Exercise 3

This code uses regex to check if the words "endangered species" appear in the 'Notes' column of `environment_df`. If it does, the corresponding row in the new '`Endangered_species`' column is marked 'Yes', otherwise 'No'. The search is case insensitive.

In [163]:
# Using regex to identify mentions of endangered species
environment_df['Endangered_species'] = environment_df['Notes'].str.contains(r'endangered species', flags=re.IGNORECASE).map({True: 'Yes', False: 'No'})

display(environment_df)

,ID,Description,Date,Location,Budget,Notes,year,Currency,Amount,Rate,Budget_USD,Endangered_species,Project_type,Country,Project_Type,Year
0,1,Forest Conservation Project in Spain,2021-03-15,"Madrid, Spain",$20000,Focusing on native forest species in Spain,2021,$,20000,1.0,20000.0,No,Conservation,Spain,Conservation,2021
1,2,River Cleanup Initiative Project 2021 in Portugal,2021-06-20,"Lisbon, Portugal",€15000,Cleanup of the Tagus river in Portugal. Endang...,2021,€,15000,1.1,16500.0,Yes,Initiative,Portugal,Initiative,2021
2,3,Urban Gardening Community Project in Germany,2022-01-11,"Berlin, Germany",€12000,"Community project in urban Berlin, Germany",2022,€,12000,1.1,13200.0,No,Community,Germany,Community,2022
3,4,Forest Reforestation Project 2022 in France,2022-04-05,"Paris, France",£18000,"Reforestation of oak trees in Paris, France",2022,£,18000,1.3,23400.0,No,Reforestation,France,Reforestation,2022
4,5,Wildlife Protection Project Plan in Italy,2023-02-22,"Rome, Italy",$25000,Plan for protecting local wildlife in Italy. E...,2023,$,25000,1.0,25000.0,Yes,Protection,Italy,Protection,2023
5,6,Endangered Species Conservation Project in Greece,2023-05-30,"Athens, Greece",€20000,Study on the impact on endangered bird species...,2023,€,20000,1.1,22000.0,No,Conservation,Greece,Conservation,2023
6,7,Wetland Restoration Project in Spain,2021-09-13,"Valencia, Spain",$17000,"Restoration of wetlands in Valencia, Spain",2021,$,17000,1.0,17000.0,No,Restoration,Spain,Restoration,2021
7,8,Marine Life Conservation Project in Portugal,2022-07-19,"Porto, Portugal",€13000,"Conservation of marine life in Porto, Portugal",2022,€,13000,1.1,14300.0,No,Conservation,Portugal,Conservation,2022
8,9,Air Quality Improvement Project Initiative in ...,2023-03-08,"Munich, Germany",€11000,Initiative for improving air quality in Munich...,2023,€,11000,1.1,12100.0,No,Improvement,Germany,Improvement,2023
9,10,Habitat Preservation Project for Birds in France,2022-11-21,"Lyon, France",£16000,"Preservation of bird habitats in Lyon, France",2022,£,16000,1.3,20800.0,No,Preservation,France,Preservation,2022

### Exercise 4

This code extracts 'Country' and 'Project Type' from the 'Location' and 'Description' columns respectively, generates a report summarising total projects and average budget by country, and identifies the top three most common project types in the dataset.

In [159]:
# Extract 'Country' from 'Location'
environment_df['Country'] = environment_df['Location'].apply(lambda x: x.split(', ')[-1])

# Extract 'Project Type' from 'Description'
environment_df['Project_Type'] = environment_df['Description'].str.extract(r'(\b\w+\b) Project')[0]

# Generate the report
report = environment_df.groupby('Country').agg(
    Total_Projects=('ID', 'count'),
    Average_Budget=('Budget_USD', 'mean')
)

# Identify top three most common project types
top_project_types = environment_df['Project_Type'].value_counts().nlargest(3).index.tolist()
report['Top_Project_Types'] = ', '.join(top_project_types)

print(report)

          Total_Projects  Average_Budget                    Top_Project_Types
Country
France                 2         22100.0  Conservation, Initiative, Community
Germany                2         12650.0  Conservation, Initiative, Community
Greece                 1         22000.0  Conservation, Initiative, Community
Italy                  1         25000.0  Conservation, Initiative, Community
Portugal               2         15400.0  Conservation, Initiative, Community
Spain                  2         18500.0  Conservation, Initiative, Community

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:140px";/>
</div>